language: go

go:
  - "1.11.x"
  - "1.12.x"

env:
  - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0

script:
  - golangci-lint run
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
